---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-svc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: discovery-rolebind
subjects:
  - kind: ServiceAccount
    name: discovery-svc
    namespace: graph-federation
roleRef:
  kind: Role
  name: discovery-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: discovery-role
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
