[package]
name = "profile"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { version = "7.0.7", features = ["tracing"] }
async-graphql-poem = "7.0.7"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
poem = "3"
tracing = "0.1"
tracing-subscriber = "0.3"
