---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infra Deps
  - nginx-gateway/
  # Graph Federation Infra
  - namespace.yaml
  - http-gateway.yaml
  - discovery/
  - services/
