---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: graph-federation
resources:
  - namespace.yaml
  - discovery.yaml
  - gateway.yaml
  - profile.yaml
  - feed.yaml
  - roles.yaml
