---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Gateway API
  - github.com/nginxinc/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.4.0
  # Nginx Gateway Fabric 1.4.0
  - github.com/nginxinc/nginx-gateway-fabric/config/crd?ref=v1.4.0
  - https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/refs/tags/v1.4.0/deploy/default/deploy.yaml
